https://simfin.com/#/

https://github.com/SimFin/simfin-tutorials

https://towardsdatascience.com/financial-data-from-yahoo-finance-with-python-b5399743bcc6

http://theautomatic.net/2020/05/05/how-to-download-fundamentals-data-with-python/

In [1]:
pip install simfin

Collecting simfinNote: you may need to restart the kernel to use updated packages.

  Downloading simfin-0.8.1-py3-none-any.whl (60 kB)
Requirement already satisfied: numpy in c:\users\petr\anaconda3\lib\site-packages (from simfin) (1.18.5)
Requirement already satisfied: pandas in c:\users\petr\anaconda3\lib\site-packages (from simfin) (1.2.1)
Requirement already satisfied: requests in c:\users\petr\anaconda3\lib\site-packages (from simfin) (2.24.0)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\petr\anaconda3\lib\site-packages (from pandas->simfin) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\petr\anaconda3\lib\site-packages (from pandas->simfin) (2020.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\petr\anaconda3\lib\site-packages (from requests->simfin) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\petr\anaconda3\lib\site-packages (from requests->simfin) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\petr\anaconda3\lib\site-packages (from requests->simfin) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\petr\anaconda3\lib\site-packages (from requests->simfin) (2.10)
Requirement already satisfied: six>=1.5 in c:\users\petr\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->simfin) (1.15.0)
Installing collected packages: simfin
Successfully installed simfin-0.8.1

API key
DLFZWSR2bd8ecJLLsGZKHhkGKImHVq6q

In [3]:
import simfin as sf

# Set your API-key for downloading data. This key gets the free data.
sf.set_api_key('free')

# Set the local directory where data-files are stored.
# The directory will be created if it does not already exist.
sf.set_data_dir('~/simfin_data/')

# Download the data from the SimFin server and load into a Pandas DataFrame.
df = sf.load_income(variant='annual', market='us')

# Print the first rows of the data.
print(df.head())

Dataset "us-income-annual" not on disk.
- Downloading ... 100.0%
- Extracting zip-file ... Done!
- Loading from disk ... Done!
                    SimFinId Currency  Fiscal Year Fiscal Period Publish Date  \
Ticker Report Date
A      2008-10-31      45846      USD         2008            FY   2008-12-19
       2009-10-31      45846      USD         2009            FY   2009-12-21
       2010-10-31      45846      USD         2010            FY   2010-12-20
       2011-10-31      45846      USD         2011            FY   2011-12-16
       2012-10-31      45846      USD         2012            FY   2012-12-20

                   Restated Date  Shares (Basic)  Shares (Diluted)  \
Ticker Report Date
A      2008-10-31     2010-12-20     363000000.0       371000000.0
       2009-10-31     2011-12-16     346000000.0       346000000.0
       2010-10-31     2012-12-20     347000000.0       353000000.0
       2011-10-31     2013-12-19     347000000.0       355000000.0
       2012-10-31     2014-12-22     348000000.0       353000000.0

                         Revenue  Cost of Revenue  ...  \
Ticker Report Date                                 ...
A      2008-10-31   5.774000e+09    -2.578000e+09  ...
       2009-10-31   4.481000e+09    -2.189000e+09  ...
       2010-10-31   5.444000e+09    -2.514000e+09  ...
       2011-10-31   6.615000e+09    -3.086000e+09  ...
       2012-10-31   6.858000e+09    -3.254000e+09  ...

                    Non-Operating Income (Loss)  Interest Expense, Net  \
Ticker Report Date
A      2008-10-31                    20000000.0            -10000000.0
       2009-10-31                   -40000000.0            -59000000.0
       2010-10-31                    -6000000.0            -76000000.0
       2011-10-31                   -39000000.0            -72000000.0
       2012-10-31                   -76000000.0            -92000000.0

                    Pretax Income (Loss), Adj.  Abnormal Gains (Losses)  \
Ticker Report Date
A      2008-10-31                    815000000                      0.0
       2009-10-31                      7000000                      0.0
       2010-10-31                    560000000              132000000.0
       2011-10-31                   1032000000                      NaN
       2012-10-31                   1043000000                      NaN

                    Pretax Income (Loss)  Income Tax (Expense) Benefit, Net  \
Ticker Report Date
A      2008-10-31              815000000                       -122000000.0
       2009-10-31                7000000                        -38000000.0
       2010-10-31              692000000                         -8000000.0
       2011-10-31             1032000000                        -20000000.0
       2012-10-31             1043000000                        110000000.0

                    Income (Loss) from Continuing Operations  \
Ticker Report Date
A      2008-10-31                                  693000000
       2009-10-31                                  -31000000
       2010-10-31                                  684000000
       2011-10-31                                 1012000000
       2012-10-31                                 1153000000

                    Net Extraordinary Gains (Losses)  Net Income  \
Ticker Report Date
A      2008-10-31                                NaN   693000000
       2009-10-31                                NaN   -31000000
       2010-10-31                                NaN   684000000
       2011-10-31                                NaN  1012000000
       2012-10-31                                NaN  1153000000

                    Net Income (Common)
Ticker Report Date
A      2008-10-31             693000000
       2009-10-31             -31000000
       2010-10-31             684000000
       2011-10-31            1012000000
       2012-10-31            1153000000

[5 rows x 26 columns]

In [4]:
df.columns

Index(['SimFinId', 'Currency', 'Fiscal Year', 'Fiscal Period', 'Publish Date',
       'Restated Date', 'Shares (Basic)', 'Shares (Diluted)', 'Revenue',
       'Cost of Revenue', 'Gross Profit', 'Operating Expenses',
       'Selling, General & Administrative', 'Research & Development',
       'Depreciation & Amortization', 'Operating Income (Loss)',
       'Non-Operating Income (Loss)', 'Interest Expense, Net',
       'Pretax Income (Loss), Adj.', 'Abnormal Gains (Losses)',
       'Pretax Income (Loss)', 'Income Tax (Expense) Benefit, Net',
       'Income (Loss) from Continuing Operations',
       'Net Extraordinary Gains (Losses)', 'Net Income',
       'Net Income (Common)'],
      dtype='object')

In [8]:
df.loc['AAPL']

,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,...,Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common)
Report Date,,,,,,,,,,,,,,,,,,,,,
2000-09-30,111052,USD,2000,FY,2000-12-21,2002-12-19,2.420866e+10,2.490018e+10,7.983000e+09,-5.817000e+09,...,2.030000e+08,NaN,823000000,269000000.0,1092000000,-3.060000e+08,786000000,NaN,786000000,786000000
2001-09-30,111052,USD,2001,FY,2001-11-11,2003-12-19,2.420866e+10,2.490018e+10,5.363000e+09,-4.128000e+09,...,2.170000e+08,NaN,-116000000,64000000.0,-52000000,1.500000e+07,-37000000,NaN,-37000000,-25000000
2002-09-30,111052,USD,2002,FY,2002-12-19,2004-12-03,2.420866e+10,2.490018e+10,5.742000e+09,-4.139000e+09,...,1.120000e+08,NaN,160000000,-73000000.0,87000000,-2.200000e+07,65000000,NaN,65000000,65000000
2003-09-30,111052,USD,2003,FY,2003-12-19,2005-12-01,2.420866e+10,2.490018e+10,6.207000e+09,-4.499000e+09,...,8.300000e+07,NaN,108000000,-16000000.0,92000000,-2.400000e+07,68000000,NaN,68000000,69000000
2004-09-30,111052,USD,2004,FY,2004-12-03,2006-12-29,2.420866e+10,2.490018e+10,8.279000e+09,-6.022000e+09,...,5.700000e+07,NaN,393000000,-23000000.0,370000000,-1.040000e+08,266000000,NaN,266000000,266000000
2005-09-30,111052,USD,2005,FY,2005-12-01,2007-11-15,2.420866e+10,2.490018e+10,1.393100e+10,-9.889000e+09,...,1.650000e+08,NaN,1808000000,NaN,1808000000,-4.800000e+08,1328000000,NaN,1328000000,1328000000
2006-09-30,111052,USD,2006,FY,2006-12-29,2008-11-05,2.420866e+10,2.490018e+10,1.931500e+10,-1.371700e+10,...,3.650000e+08,NaN,2818000000,NaN,2818000000,-8.290000e+08,1989000000,NaN,1989000000,1989000000
2007-09-30,111052,USD,2007,FY,2007-11-15,2009-10-27,2.420866e+10,2.490018e+10,2.400600e+10,-1.585200e+10,...,5.990000e+08,NaN,5008000000,NaN,5008000000,-1.512000e+09,3496000000,NaN,3496000000,3496000000
2008-09-30,111052,USD,2008,FY,2008-11-05,2010-10-27,2.468458e+10,2.525989e+10,3.749100e+10,-2.429400e+10,...,6.200000e+08,NaN,8947000000,NaN,8947000000,-2.828000e+09,6119000000,NaN,6119000000,6119000000
2009-09-30,111052,USD,2009,FY,2009-10-25,2011-10-26,2.500445e+10,2.539614e+10,4.290500e+10,-2.568300e+10,...,3.260000e+08,NaN,12066000000,NaN,12066000000,-3.831000e+09,8235000000,NaN,8235000000,8235000000
2010-09-30,111052,USD,2010,FY,2010-10-27,2012-10-31,2.546491e+10,2.589194e+10,6.522500e+10,-3.954100e+10,...,1.550000e+08,NaN,18540000000,NaN,18540000000,-4.527000e+09,14013000000,NaN,14013000000,14013000000
2011-09-30,111052,USD,2011,FY,2011-10-26,2013-10-30,2.587922e+10,2.622606e+10,1.082490e+11,-6.443100e+10,...,4.150000e+08,NaN,34205000000,NaN,34205000000,-8.283000e+09,25922000000,NaN,25922000000,25922000000
2012-09-30,111052,USD,2012,FY,2012-10-31,2014-10-27,2.617490e+10,2.646993e+10,1.565080e+11,-8.784600e+10,...,5.220000e+08,NaN,55763000000,NaN,55763000000,-1.403000e+10,41733000000,NaN,41733000000,41733000000
2013-09-30,111052,USD,2013,FY,2013-10-30,2015-10-28,2.590928e+10,2.608654e+10,1.709100e+11,-1.066060e+11,...,1.156000e+09,NaN,50155000000,NaN,50155000000,-1.311800e+10,37037000000,NaN,37037000000,37037000000
2014-09-30,111052,USD,2014,FY,2014-10-27,2016-10-26,2.434229e+10,2.449065e+10,1.827950e+11,-1.122580e+11,...,9.800000e+08,NaN,53483000000,NaN,53483000000,-1.397300e+10,39510000000,NaN,39510000000,39510000000
2015-09-30,111052,USD,2015,FY,2015-10-28,2017-11-03,2.301368e+10,2.317228e+10,2.337150e+11,-1.400890e+11,...,1.285000e+09,NaN,72515000000,NaN,72515000000,-1.912100e+10,53394000000,NaN,53394000000,53394000000
2016-09-30,111052,USD,2016,FY,2016-10-26,2018-11-05,2.188328e+10,2.200112e+10,2.156390e+11,-1.313760e+11,...,1.348000e+09,NaN,61372000000,NaN,61372000000,-1.568500e+10,45687000000,NaN,45687000000,45687000000
2017-09-30,111052,USD,2017,FY,2017-11-03,2019-10-31,2.086897e+10,2.100677e+10,2.292340e+11,-1.410480e+11,...,2.745000e+09,NaN,64089000000,NaN,64089000000,-1.573800e+10,48351000000,NaN,48351000000,48351000000
2018-09-30,111052,USD,2018,FY,2018-11-05,2019-10-31,1.982151e+10,2.000044e+10,2.655950e+11,-1.637560e+11,...,2.005000e+09,NaN,72903000000,NaN,72903000000,-1.337200e+10,59531000000,NaN,59531000000,59531000000
2019-09-30,111052,USD,2019,FY,2019-10-31,2019-10-31,1.847134e+10,1.859565e+10,2.601740e+11,-1.617820e+11,...,1.807000e+09,NaN,65737000000,NaN,65737000000,-1.048100e+10,55256000000,NaN,55256000000,55256000000