https://simfin.com/#/

https://github.com/SimFin/simfin-tutorials

https://towardsdatascience.com/financial-data-from-yahoo-finance-with-python-b5399743bcc6

http://theautomatic.net/2020/05/05/how-to-download-fundamentals-data-with-python/

In [1]:
pip install simfin

Collecting simfinNote: you may need to restart the kernel to use updated packages.

  Downloading simfin-0.8.1-py3-none-any.whl (60 kB)
Requirement already satisfied: numpy in c:\users\petr\anaconda3\lib\site-packages (from simfin) (1.18.5)
Requirement already satisfied: pandas in c:\users\petr\anaconda3\lib\site-packages (from simfin) (1.2.1)
Requirement already satisfied: requests in c:\users\petr\anaconda3\lib\site-packages (from simfin) (2.24.0)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\petr\anaconda3\lib\site-packages (from pandas->simfin) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\petr\anaconda3\lib\site-packages (from pandas->simfin) (2020.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\petr\anaconda3\lib\site-packages (from requests->simfin) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\petr\anaconda3\lib\site-packages (from requests->simfin) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\petr\anaconda3\lib\site-packages (from requests->simfin) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\petr\anaconda3\lib\site-packages (from requests->simfin) (2.10)
Requirement already satisfied: six>=1.5 in c:\users\petr\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->simfin) (1.15.0)
Installing collected packages: simfin
Successfully installed simfin-0.8.1

In [5]:
pip install python-dotenv

Collecting python-dotenv
  Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.0.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [50]:
from dotenv import load_dotenv
load_dotenv()

True

In [52]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [56]:
import sys
import os

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from app import FinanceLib as fl

In [54]:
print(sys.path)

['C:\\Projects\\FinanceProject\\ipynb', 'C:\\Program Files\\Python39\\python39.zip', 'C:\\Program Files\\Python39\\DLLs', 'C:\\Program Files\\Python39\\lib', 'C:\\Program Files\\Python39', 'C:\\Projects\\finance-venv', '', 'C:\\Projects\\finance-venv\\lib\\site-packages', 'C:\\Projects\\finance-venv\\lib\\site-packages\\win32', 'C:\\Projects\\finance-venv\\lib\\site-packages\\win32\\lib', 'C:\\Projects\\finance-venv\\lib\\site-packages\\Pythonwin', 'C:\\Projects\\FinanceProject']

In [2]:
import simfin as sf

In [3]:
import os
home_directory = os.path.expanduser("~")
print(home_directory)

C:\Users\p.kravchuk

In [9]:
simfin_api_key = os.getenv("SIMFIN_API_KEY")

In [14]:
import simfin as sf

# Set your API-key for downloading data. This key gets the free data.
sf.set_api_key(simfin_api_key)

# Set the local directory where data-files are stored.
# The directory will be created if it does not already exist.
sf.set_data_dir('~/simfin_data/')

In [21]:
# Download the data from the SimFin server and load into a Pandas DataFrame.
df_quarterly = sf.load_income(variant='quarterly', market='us')

Dataset "us-income-quarterly" on disk (0 days old).
- Loading from disk ...

C:\Projects\finance-venv\lib\site-packages\simfin\load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,

Done!

In [20]:
df_annual = sf.load_income(variant='annual', market='us')

Dataset "us-income-annual" on disk (105 days old).
- Downloading ... 100.0%
- Extracting zip-file ... Done!
- Loading from disk ...

C:\Projects\finance-venv\lib\site-packages\simfin\load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,

Done!

In [66]:
df_quarterly.columns

Index(['Ticker', 'SimFinId', 'Currency', 'Fiscal Year', 'Fiscal Period',
       'Publish Date', 'Restated Date', 'Shares (Basic)', 'Shares (Diluted)',
       'Revenue', 'Cost of Revenue', 'Gross Profit', 'Operating Expenses',
       'Selling, General & Administrative', 'Research & Development',
       'Depreciation & Amortization', 'Operating Income (Loss)',
       'Non-Operating Income (Loss)', 'Interest Expense, Net',
       'Pretax Income (Loss), Adj.', 'Abnormal Gains (Losses)',
       'Pretax Income (Loss)', 'Income Tax (Expense) Benefit, Net',
       'Income (Loss) from Continuing Operations',
       'Net Extraordinary Gains (Losses)', 'Net Income',
       'Net Income (Common)'],
      dtype='object')

In [67]:
df_quarterly.index

DatetimeIndex(['2018-09-30', '2018-09-30', '2018-09-30', '2018-09-30',
               '2018-09-30', '2018-09-30', '2018-09-30', '2018-09-30',
               '2018-09-30', '2018-09-30',
               ...
               '2023-07-31', '2023-07-31', '2023-07-31', '2023-07-31',
               '2023-07-31', '2023-07-31', '2023-07-31', '2023-07-31',
               '2023-07-31', '2023-07-31'],
              dtype='datetime64[ns]', name='Report Date', length=57719, freq=None)

In [24]:
df_quarterly.index.min(), df_quarterly.index.max()

(('A', Timestamp('2018-10-31 00:00:00')),
 ('ZYXI', Timestamp('2023-06-30 00:00:00')))

In [25]:
df_annual.index.min(), df_annual.index.max()

(('A', Timestamp('2018-10-31 00:00:00')),
 ('ZYXI', Timestamp('2022-12-31 00:00:00')))

In [26]:
df_quarterly.head()

                    SimFinId Currency  Fiscal Year Fiscal Period Publish Date  \
Ticker Report Date
A      2018-10-31      45846      USD         2018            Q4   2018-12-20
       2019-01-31      45846      USD         2019            Q1   2019-03-05
       2019-04-30      45846      USD         2019            Q2   2019-05-30
       2019-07-31      45846      USD         2019            Q3   2019-08-30
       2019-10-31      45846      USD         2019            Q4   2019-12-19

                   Restated Date  Shares (Basic)  Shares (Diluted)  \
Ticker Report Date
A      2018-10-31     2020-12-18     319000000.0       327000000.0
       2019-01-31     2019-03-05     318000000.0       322000000.0
       2019-04-30     2019-05-30     317000000.0       321000000.0
       2019-07-31     2019-08-30     312000000.0       316000000.0
       2019-10-31     2019-08-30     309000000.0       313000000.0

                         Revenue  Cost of Revenue  ...  \
Ticker Report Date                                 ...
A      2018-10-31   1.294000e+09     -585679379.0  ...
       2019-01-31   1.284000e+09     -577000000.0  ...
       2019-04-30   1.238000e+09     -569000000.0  ...
       2019-07-31   1.274000e+09     -582000000.0  ...
       2019-10-31   1.367000e+09     -630000000.0  ...

                    Non-Operating Income (Loss)  Interest Expense, Net  \
Ticker Report Date
A      2018-10-31                    19000000.0             -8000000.0
       2019-01-31                    -2000000.0             -8000000.0
       2019-04-30                     2000000.0             -7000000.0
       2019-07-31                    -3000000.0             -8000000.0
       2019-10-31                   -19000000.0            -15000000.0

                    Pretax Income (Loss), Adj.  Abnormal Gains (Losses)  \
Ticker Report Date
A      2018-10-31                  244000000.0                      NaN
       2019-01-31                  248000000.0                      NaN
       2019-04-30                  218000000.0                      NaN
       2019-07-31                  222000000.0                      NaN
       2019-10-31                  231000000.0                      NaN

                    Pretax Income (Loss)  Income Tax (Expense) Benefit, Net  \
Ticker Report Date
A      2018-10-31              244000000                        -49000000.0
       2019-01-31              248000000                        256000000.0
       2019-04-30              218000000                        -36000000.0
       2019-07-31              222000000                        -31000000.0
       2019-10-31              231000000                        -37000000.0

                    Income (Loss) from Continuing Operations  \
Ticker Report Date
A      2018-10-31                                  195000000
       2019-01-31                                  504000000
       2019-04-30                                  182000000
       2019-07-31                                  191000000
       2019-10-31                                  194000000

                    Net Extraordinary Gains (Losses)  Net Income  \
Ticker Report Date
A      2018-10-31                                NaN   195000000
       2019-01-31                                NaN   504000000
       2019-04-30                                NaN   182000000
       2019-07-31                                NaN   191000000
       2019-10-31                                NaN   194000000

                    Net Income (Common)
Ticker Report Date
A      2018-10-31             195000000
       2019-01-31             504000000
       2019-04-30             182000000
       2019-07-31             191000000
       2019-10-31             194000000

[5 rows x 26 columns]

In [28]:
REPORT_DATE = 'Report Date'
PUBLISH_DATE = 'Publish Date'
RESTATED_DATE = 'Restated Date'
df_quarterly = sf.load(dataset='income', variant='quarterly', market='us',
              index=[REPORT_DATE],
              parse_dates=[REPORT_DATE, PUBLISH_DATE, RESTATED_DATE])

Dataset "us-income-quarterly" on disk (0 days old).
- Loading from disk ...

C:\Projects\finance-venv\lib\site-packages\simfin\load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,

Done!

In [34]:
df_quarterly.head()

,Ticker,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,...,Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common)
Report Date,,,,,,,,,,,,,,,,,,,,,
2018-09-30,METC,7962936,USD,2018,Q3,2018-11-07,2019-11-05,4.008247e+07,4.032931e+07,62166000.0,...,470000.0,-566000.0,6398000.0,-124000.0,6274000,-63000.0,6211000,NaN,6211000,6211000
2018-09-30,MIDD,993573,USD,2018,Q3,2018-11-07,2019-11-07,5.557700e+07,5.557700e+07,713331000.0,...,-18883000.0,-19143000.0,98198653.0,9225000.0,98019000,-25114000.0,72905000,NaN,72905000,72905000
2018-09-30,AOS,445771,USD,2018,Q3,2018-11-08,2018-11-08,1.705079e+08,1.720846e+08,754100000.0,...,3100000.0,-2000000.0,131500000.0,NaN,131500000,-26900000.0,104600000,NaN,104600000,104600000
2018-09-30,MICR,706150,USD,2018,Q3,2018-11-13,2018-11-13,2.853111e+09,2.853111e+09,5001660.0,...,-88613.0,-101439.0,-77171.0,NaN,-77171,0.0,-77171,NaN,-77171,-77171
2018-09-30,MIC,345220,USD,2018,Q3,2018-10-31,2018-10-31,8.537809e+07,8.539857e+07,473280000.0,...,-50514000.0,-32503000.0,44808000.0,-15548000.0,29260000,-7884000.0,21376000,NaN,21704000,21704000

In [32]:
df_quarterly.index.min(), df_quarterly.index.max()

(Timestamp('2018-09-30 00:00:00'), Timestamp('2023-07-31 00:00:00'))

In [41]:
df_quarterly.groupby('Ticker').agg({'Ticker': 'count'})

              Ticker
Ticker
A                 20
AA                20
AAC               10
AACI               2
AAC_delisted       5
...              ...
ZVIA               9
ZVO               17
ZY                 7
ZYNE              20
ZYXI              20

[3878 rows x 1 columns]

In [45]:
import pandas as pd

In [46]:
pd.set_option('display.max_columns', None)

In [48]:
df_quarterly.size

1558413

In [47]:
df_quarterly[df_quarterly['Ticker'] == 'AAPL']

,Ticker,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",Research & Development,Depreciation & Amortization,Operating Income (Loss),Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common)
Report Date,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-09-30,AAPL,111052,USD,2018,Q4,2018-11-05,2020-10-30,1.920635e+10,1.939019e+10,6.290000e+10,-3.881600e+10,2.408400e+10,-7.966000e+09,-4.216000e+09,-3.750000e+09,NaN,1.611800e+10,303000000.0,442739444.0,1.642100e+10,NaN,16421000000,-2.296000e+09,14125000000,NaN,14125000000,14125000000
2018-12-31,AAPL,111052,USD,2019,Q1,2019-01-30,2020-01-29,1.894328e+10,1.909301e+10,8.431000e+10,-5.227900e+10,3.203100e+10,-8.685000e+09,-4.783000e+09,-3.902000e+09,NaN,2.334600e+10,560000000.0,416301193.0,2.390600e+10,NaN,23906000000,-3.941000e+09,19965000000,NaN,19965000000,19965000000
2019-03-31,AAPL,111052,USD,2019,Q2,2019-05-01,2020-05-01,1.869628e+10,1.880258e+10,5.801500e+10,-3.619400e+10,2.182100e+10,-8.406000e+09,-4.458000e+09,-3.948000e+09,NaN,1.341500e+10,378000000.0,347872558.0,1.379300e+10,NaN,13793000000,-2.232000e+09,11561000000,NaN,11561000000,11561000000
2019-06-30,AAPL,111052,USD,2019,Q3,2019-07-31,2020-07-31,1.828253e+10,1.840552e+10,5.380900e+10,-3.358200e+10,2.022700e+10,-8.683000e+09,-4.426000e+09,-4.257000e+09,NaN,1.154400e+10,367000000.0,324185526.0,1.191100e+10,NaN,11911000000,-1.867000e+09,10044000000,NaN,10044000000,10044000000
2019-09-30,AAPL,111052,USD,2019,Q4,2019-10-31,2021-10-29,1.796325e+10,1.808150e+10,6.404000e+10,-3.972700e+10,2.431300e+10,-8.688000e+09,-4.578000e+09,-4.110000e+09,NaN,1.562500e+10,502000000.0,295590714.0,1.612700e+10,NaN,16127000000,-2.441000e+09,13686000000,NaN,13686000000,13686000000
2019-12-31,AAPL,111052,USD,2020,Q1,2020-01-29,2021-01-28,1.766016e+10,1.781842e+10,9.181900e+10,-5.660200e+10,3.521700e+10,-9.648000e+09,-5.197000e+09,-4.451000e+09,NaN,2.556900e+10,349000000.0,259501861.0,2.591800e+10,NaN,25918000000,-3.682000e+09,22236000000,NaN,22236000000,22236000000
2020-03-31,AAPL,111052,USD,2020,Q2,2020-05-01,2021-04-29,1.744040e+10,1.761876e+10,5.831300e+10,-3.594300e+10,2.237000e+10,-9.517000e+09,-4.952000e+09,-4.565000e+09,NaN,1.285300e+10,282000000.0,291924414.0,1.313500e+10,NaN,13135000000,-1.886000e+09,11249000000,NaN,11249000000,11249000000
2020-06-30,AAPL,111052,USD,2020,Q3,2020-07-31,2021-07-28,1.725029e+10,1.741915e+10,5.968500e+10,-3.700500e+10,2.268000e+10,-9.589000e+09,-4.831000e+09,-4.758000e+09,NaN,1.309100e+10,46000000.0,204462365.0,1.313700e+10,NaN,13137000000,-1.884000e+09,11253000000,NaN,11253000000,11253000000
2020-09-30,AAPL,111052,USD,2020,Q4,2020-10-30,2021-07-28,1.705762e+10,1.725652e+10,6.469800e+10,-4.000900e+10,2.468900e+10,-9.914000e+09,-4.936000e+09,-4.978000e+09,NaN,1.477500e+10,126000000.0,133701127.0,1.490100e+10,NaN,14901000000,-2.228000e+09,12673000000,NaN,12673000000,12673000000
2020-12-31,AAPL,111052,USD,2021,Q1,2021-01-28,2022-01-28,1.693512e+10,1.711369e+10,1.114390e+11,-6.711100e+10,4.432800e+10,-1.079400e+10,-5.631000e+09,-5.163000e+09,NaN,3.353400e+10,45000000.0,108764057.0,3.357900e+10,NaN,33579000000,-4.824000e+09,28755000000,NaN,28755000000,28755000000
2021-03-31,AAPL,111052,USD,2021,Q2,2021-04-29,2022-04-29,1.675348e+10,1.692916e+10,8.958400e+10,-5.150500e+10,3.807900e+10,-1.057600e+10,-5.314000e+09,-5.262000e+09,NaN,2.750300e+10,508000000.0,48105438.0,2.801100e+10,NaN,28011000000,-4.381000e+09,23630000000,NaN,23630000000,23630000000
2021-06-30,AAPL,111052,USD,2021,Q3,2021-07-28,2022-07-29,1.684430e+10,1.702142e+10,8.143400e+10,-4.617900e+10,3.525500e+10,-1.112900e+10,-5.412000e+09,-5.717000e+09,NaN,2.412600e+10,243000000.0,54104465.0,2.436900e+10,NaN,24369000000,-2.625000e+09,21744000000,NaN,21744000000,21744000000
2021-09-30,AAPL,111052,USD,2021,Q4,2021-10-29,2022-07-29,1.639172e+10,1.651929e+10,8.336000e+10,-4.818600e+10,3.517400e+10,-1.138800e+10,-5.616000e+09,-5.772000e+09,NaN,2.378600e+10,-538000000.0,-12996967.0,2.324800e+10,NaN,23248000000,-2.697000e+09,20551000000,NaN,20551000000,20551000000
2021-12-31,AAPL,111052,USD,2022,Q1,2022-01-28,2023-02-03,1.639172e+10,1.651929e+10,1.239450e+11,-6.970200e+10,5.424300e+10,-1.275500e+10,-6.449000e+09,-6.306000e+09,NaN,4.148800e+10,-247000000.0,-43920174.0,4.124100e+10,NaN,41241000000,-6.611000e+09,34630000000,NaN,34630000000,34630000000
2022-03-31,AAPL,111052,USD,2022,Q2,2022-04-29,2023-05-05,1.639172e+10,1.651929e+10,9.727800e+10,-5.471900e+10,4.255900e+10,-1.258000e+10,-6.193000e+09,-6.387000e+09,NaN,2.997900e+10,160000000.0,9006452.0,3.013900e+10,NaN,30139000000,-5.129000e+09,25010000000,NaN,25010000000,25010000000
2022-06-30,AAPL,111052,USD,2022,Q3,2022-07-29,2023-08-04,1.616294e+10,1.626220e+10,8.295900e+10,-4.707400e+10,3.588500e+10,-1.280900e+10,-6.012000e+09,-6.797000e+09,NaN,2.307600e+10,-10000000.0,2999746.0,2.306600e+10,NaN,23066000000,-3.624000e+09,19442000000,NaN,19442000000,19442000000
2022-09-30,AAPL,111052,USD,2022,Q4,2022-10-28,2023-08-04,1.621596e+10,1.632582e+10,9.014600e+10,-5.205100e+10,3.809500e+10,-1.320100e+10,-6.440000e+09,-6.761000e+09,NaN,2.489400e+10,-237000000.0,-74177977.0,2.465700e+10,NaN,24657000000,-3.936000e+09,20721000000,NaN,20721000000,20721000000
2022-12-31,AAPL,111052,USD,2023,Q1,2023-02-03,2024-02-02,1.589272e+10,1.595572e+10,1.171540e+11,-6.682200e+10,5.033200e+10,-1.431600e+10,-6.607000e+09,-7.709000e+09,NaN,3.601600e+10,-393000000.0,-134899308.0,3.562300e+10,NaN,35623000000,-5.625000e+09,29998000000,NaN,29998000000,29998000000
2023-03-31,AAPL,111052,USD,2023,Q2,2023-05-05,2024-05-03,1.578715e+10,1.584705e+10,9.483600e+10,-5.286000e+10,4.197600e+10,-1.365800e+10,-6.201000e+09,-7.457000e+09,NaN,2.831800e+10,64000000.0,-11989290.0,2.838200e+10,NaN,28382000000,-4.222000e+09,24160000000,NaN,24160000000,24160000000
2023-06-30,AAPL,111052,USD,2023,Q3,2023-08-04,2023-08-04,1.569761e+10,1.577502e+10,8.179700e+10,-4.538400e+10,3.641300e+10,-1.341500e+10,-5.973000e+09,-7.442000e+09,NaN,2.299800e+10,-265000000.0,-18018416.0,2.273300e+10,NaN,22733000000,-2.852000e+09,19881000000,NaN,19881000000,19881000000

In [60]:
from app import FinanceLib as fl

In [78]:
table_name = 'income'
schema_name = 'finance'
# Create SQLAlchemy engine
engine = fl.get_conn_pg_engine(False)

In [74]:
income_tickers = df_quarterly.groupby('Ticker').agg({'Ticker': 'count'})
income_tickers = income_tickers.rename(columns={'Ticker': 'CountRows'})

In [75]:
income_tickers.head()

              CountRows
Ticker
A                    20
AA                   20
AAC                  10
AACI                  2
AAC_delisted          5

In [76]:
for ticker in income_tickers.index:
    df_ticker = df_quarterly[df_quarterly['Ticker'] == ticker]
#     df_ticker = df_quarterly[df_quarterly['Ticker'] == 'MSFT']
    df_ticker = finance_stat_rename_columns('income', df_ticker)
    df_ticker = df_ticker.reset_index("report_date")
    merge_df_to_pg(df_ticker, engine, table_name, schema_name, merge_key)

A
AA
AAC
AACI
AAC_delisted
AAL
AAMC
AAOI
AAP
AAPL
AAT
AAWH
AAWW
ABBV
ABCD
ABCL
ABEO
ABG
ABIO
ABMC
ABMD
ABNB
ABOS
ABSI
ABT
ABTL
ABUS
ABVC
AC
ACA
ACAC
ACAD
ACAH
ACAN
ACAQ
ACBA
ACC
ACCO
ACEL
ACER
ACET
ACET_delisted
ACHC
ACHR
ACHV
ACI
ACIA
ACIW
ACLS
ACLX
ACM
ACMR
ACN
ACOR
ACRE
ACRO
ACRS
ACRX
ACST
ACTG
ACU
ACVA
ACXP
ADAP
ADBE
ADC
ADER
ADES
ADI
ADIL
ADM
ADMA
ADMP
ADMS
ADNT
ADOM
ADP
ADRA
ADRT
ADSK
ADT
ADTN
ADUS
ADV
ADVM
AE
AEE
AEHA
AEHR
AEMD
AEO
AEP
AERC
AERG
AERI
AES
AESE
AESI
AEVA
AFCG
AFGS
AFI
AFRM
AGCO
AGEN
AGFS
AGHI
AGIO
AGM
AGN
AGNC
AGR
AGS
AGTI
AGX
AGYS
AH
AHCO
AHH
AHPI
AI
AIM
AIMC
AIMD
AIP
AIR
AIRC
AIRG
AIRS
AIRTP
AIT
AIV
AJG
AJIA
AJRD
AKA
AKAM
AKBA
AKLI
AKOM
AKRO
AKRX
AKS
AKYA
AL
ALB
ALBO
ALCC
ALCO
ALDX
ALE
ALEC
ALEX
ALG
ALGM
ALGN
ALGS
ALGT
ALHC
ALIM
ALJJ
ALK
ALKS
ALKT
ALLE
ALLK
ALLO
ALNA
ALNY
ALPA
ALPN
ALRM
ALRN
ALSK
ALSN
ALT
ALTG
ALTM
ALTMS
ALTO
ALTR
ALUR
ALVR
ALX
ALXN
ALXO
ALZN
AMAM
AMAT
AMC
AMCIU
AMCR
AMCX
AMD
AME
AMED
AMG
AMGN
AMH
AMHCU
AMK
AMKR
AMLX
AMN
AMOT
AMP
AMPE
AMPH
AMPL
AMPY
AMR
AMRC
AMRN
AMRS
AMRX
AMSC
AMSWA
AMT
AMTD
AMTX
AMWD
AMWL
AMZN
AN
ANAB
ANDE
ANET
ANF
ANGI
ANGO
ANIK
ANIP
ANIX
ANNX
ANSS
ANVS
ANY
ANZU
AOMR
AON
AORT
AOS
AOUT
AP
APA
APAM
APC
APD
APDN
APEI
APEN
APG
APGE
APH
APHE
APLD
APLS
APLT
APMI
APO
APOG
APOP
APP
APPF
APPH
APPN
APPS
APRE
APRN
APT
APTI
APTV
APTX
APU
APVO
APXI
APY
APYX
AQB
AQMS
AQST
AQUA
AR
ARA
ARAV
ARAY
ARC
ARCB
ARCH
ARCT
ARCW
ARDX
AREC
AREX
ARHS
ARIS
ARKO
ARKR
ARL
ARLO
ARLP
ARMK
ARMP
ARNA
ARNC
AROC
ARPO
ARQL
ARQT
ARRW
ARRY
ARRY_delisted
ARTE
ARTNA
ARTX
ARVN
ARW
ARWR
ASAN
ASCMA
ASFH
ASGN
ASIX
ASLE
ASMB
ASNA
ASO
ASPN
ASPU
ASRT
ASTC
ASTE
ASTR
ASTS
ASUR
ASXC
ASYS
ATCX
ATEC
ATEN
ATER
ATEX
ATGE
ATHA
ATHN_delisted
ATHX
ATI
ATKR
ATLC
ATMU
ATNI
ATNM
ATNX
ATO
ATOM
ATOS
ATR
ATRA
ATRC
ATRI
ATRO
ATRS
ATSG
ATUS
ATVCU
ATVI
ATXG
ATXS
AUGG
AUGX
AUMN
AUPH
AUR
AURA
AUVI
AVAC
AVAH
AVAV
AVB
AVD
AVDL
AVDX
AVEO
AVGO
AVGR
AVID
AVIR
AVLR
AVMR
AVNS
AVNT
AVP
AVPT
AVRO
AVT
AVTE
AVTR
AVY
AVYA
AWI
AWK
AWR
AWRE
AXAS
AXDX
AXGN
AXL
AXNX
AXON
AXSM
AXTA
AXTI
AY
AYI
AYX
AZEK
AZPN
AZTR
AZYO
AZZ
B
BA
BACA
BAH
BALL
BALY
BAND
BARK
BASE
BATL
BAX
BB
BBBY
BBCP
BBDC
BBGI
BBIO
BBLR
BBQ
BBSI
BBWI
BBY
BC
BCAB
BCAC
BCC
BCEI_delisted
BCEL
BCO
BCOR
BCOV
BCPC
BCRX
BCSF
BCYC
BCYP
BDC
BDN
BDSI
BDSX
BDTX
BDX
BE
BEAM
BEAT
BECN
BEEM
BELFB
BEN
BENF
BERY
BFAM
BFLY
BFS
BG
BGCP
BGFV
BGG
BGNE
BGRY
BGS
BGSF
BGSX
BH
BHAC
BHC
BHE
BHI
BHIL
BHR
BHVN
BID
BIG
BIGC
BIIB
BIO
BIRD
BIVI
BIXT
BJRI
BKCC
BKD
BKE
BKH
BKI
BKKT
BKNG
BKR
BKS
BKTI
BKUH
BL
BLBD
BLCM
BLCO
BLD
BLDE
BLDR
BLFS
BLI
BLIN
BLK
BLKB
BLMN
BLND
BLNK
BLPH
BLUE
BLZE
BMAC
BMAQ
BMBL
BMEA
BMI
BMRA
BMRN
BMS
BMY
BNED
BNFT
BNGO
BNL
BNNR
BNTC
BODY
BOJA
BOLT
BOMN
BOOM
BOOT
BOX
BOXL
BPL
BPMC
BPMP
BR
BRACU
BRBR
BRC
BRDG
BREW
BRFH
BRIV
BRK-A
BRKHU
BRKR
BRKS
BRLT
BRMK
BRN
BRO
BROS
BRP
BRS
BRSP
BRSS
BRT
BRX
BRZE
BSET
BSIG
BSM
BSQR
BSTC
BSTG
BSX
BSY
BTAI
BTCS
BTU
BURL
BV
BVH
BVS
BVSN
BW
BWA
BWAQ
BWEN
BWLA
BWMN
BWV
BWXT
BX
BXP
BYD
BYND
BYRN
BZFD
BZH
CAAS
CABA
CABO
CACC
CACI
CAG
CAH
CAI
CAKE
CAL
CALA
CALL
CALX
CAMP
CANO
CAPC
CAPL
CAPR
CARA
CARR
CARS
CASA
CASI
CASS
CASY
CAT
CATM
CATN
CATO
CAVA
CA_delisted
CBAT
CBAY
CBB
CBIO
CBKCQ
CBLI
CBLK
CBM
CBOE
CBRE
CBRL
CBZ
CC
CCAIU
CCAP
CCCC
CCCS
CCF
CCFI
CCH
CCHWF
CCI
CCK
CCL
CCLP
CCMP
CCO
CCOI
CCRD
CCRN
CCS
CCSI
CCTC
CCV
CCXI
CCYC
CDAK
CDAY
CDE
CDK
CDLX
CDMO
CDNA
CDNS
CDRE
CDW
CDXC
CDXS
CDZI
CE
CECE
CEG
CELG
CELH
CELU
CEMI
CENT
CEQP
CERE
CERN
CERS
CERT
CETV
CEVA
CF
CFIV
CFLT
CFMS
CFRX
CFX
CG
CGA
CGEM
CGNX
CGRN
CGTX
CHAP
CHAQ
CHART
CHCI
CHD
CHDN
CHE
CHEF
CHGG
CHH
CHK
CHKE
CHMI
CHNG
CHRA
CHRS
CHRW
CHS
CHSP
CHTR
CHUY
CHWY
CIDM
CIEN
CIFR
CIIG
CIM
CINC
CINR
CIR
CIVI
CK0000081061
CK0001584423
CKPT
CL
CLAR
CLAY
CLBR
CLBS
CLCT
CLDR
CLDX
CLF
CLFD
CLGX
CLH
CLIR
CLNE
CLNN
CLOEU
CLOV
CLPR
CLPT
CLR
CLRB
CLSD
CLSK
CLSN
CLUBQ
CLVS
CLVT
CLW
CLX
CMAX
CMBG
CMBM
CMC
CMCO
CMCSA
CMD
CME
CMG
CMI
CMLF
CMLS
CMP
CMPR
CMPS
CMPX
CMRX
CMS
CMT
CMTG
CNC
CNCE
CNDA
CNGLU
CNK
CNLPL
CNM
CNMD
CNNE
CNNX
CNP
CNR
CNS
CNST
CNTA
CNTX
CNTY
CNX
CNXC
CNXN
COCO
CODI
CODQL
CODX
COGT
COHR
COIN
COKE
COL
COLD
COLM
COMM
COMP
CONE
CONN
COO
COOK
COP
COR
CORR
CORT
COR_delisted
COST
COTY
COUP
COUR
COYA
CP
CPAAU
CPB
CPE
CPHC
CPHI
CPIX
CPK
CPLG
CPN
CPNG
CPRI
CPRT
CPRX
CPS
CPSI
CPSR
CPSS
CPUH
CQCQ
CQP
CR
CRAI
CRAWA
CRAY
CRBP
CRBU
CRC
CRCT
CRD-A
CRDO
CREG
CRGE
CRGY
CRI
CRIS
CRK
CRL
CRM
CRMD
CRMT
CRMZ
CRNC
CRNX
CROX
CRR
CRS
CRSP
CRSR
CRTO
CRUS
CRVL
CRVS
CRWD
CRZO
CSBR
CSCO
CSGP
CSGS
CSII
CSL
CSLT
CSOD
CSPI
CSPR
CSR
CSS
CSSE
CSTL
CSU
CSV
CSWI
CSX
CTA-PB
CTAS
CTGO
CTG_delisted
CTHR
CTIC
CTKB
CTLP
CTLT
CTM
CTNT
CTOS
CTRA
CTRE
CTRN
CTS
CTSH
CTSO
CTT
CTV
CTVA
CTXR
CTXS
CUB
CUBE
CUE
CUK
CULP
CUO
CURO
CURV
CUTR
CUZ
CVA
CVCO
CVGI
CVII
CVKD
CVLG
CVLT
CVM
CVNA
CVRX
CVS
CVSI
CVT
CVV
CVX
CW
CWAN
CWBHF
CWBR
CWEN
CWGL
CWH
CWK
CWT
CXDO
CXM
CXO
CXP
CXW
CY
CYAN
CYCA
CYCC
CYCN
CYH
CYIG
CYN
CYTK
CZR
D
DAKT
DAL
DALN
DALS
DAN
DAR
DASH
DATA
DAWN
DBDR
DBGI
DBI
DBRG
DBVT
DCGO
DCI
DCO
DCPH
DCT
DCTH
DD
DDD
DDE
DDOG
DDS
DE
DEA
DECK
DEI
DELL
DEN
DENN
DESTQ
DEVV
DFCO
DFH
DFIN
DFNS
DFODQ
DFPH
DG
DGII
DGX
DH
DHI
DHIL
DHR
DHX
DIBS
DICE
DIN
DINO
DIOD
DIS
DISH
DIT
DJCO
DK
DKL
DKNG
DKS
DLA
DLB
DLHC
DLPH
DLR
DLTH
DLTR
DLX
DM
DMAC
DMLP
DMRC
DMTK
DMYS
DNAY
DNB
DNKN
DNLI
DNMR
DNOW
DNUT
DOC
DOCS
DOCU
DOMO
DOOR
DORM
DOUG
DOV
DOW
DPLO
DPZ
DRE
DRFS
DRH
DRI
DRIO
DRNA
DRQ
DRRX
DRTT
DS
DSAQ
DSKE
DSP
DT
DTC
DTE
DTEA
DTIL
DTOC
DTRM
DTSS
DUK
DUOL
DV
DVA
DVAX
DVN
DWACU
DX
DXC
DXCM
DXLG
DXPE
DXYN
DY
DYN
DYNS
DYNT
DZSI
EA
EACO
EAF
EAR
EAST
EAT
EB
EBAY
EBF
EBIX
ECA
ECHO
ECL
ECOM
ECOR
ECYT
ED
EDIT
EDNT
EDR
EEI
EEX
EE_delisted
EFC
EFOI
EFTR
EFX
EG
EGAN
EGGF
EGHT
EGLE
EGLT
EGP
EGRX
EGY
EHTH
EIGI
EIGR
EIX
EKSO
EL
ELA
ELAN
ELDN
ELF
ELLI
ELMD
ELOX
ELS
ELSE
ELVT
ELY
ELYM
EMAN
EME
EMKR
EML
EMMS
EMN
EMP
EMR
ENB
ENBL
ENDP
ENER
ENFN
ENG
ENLC
ENO
ENPH
ENR
ENS
ENSC
ENSG
ENSV
ENTA
ENTG
ENTX
ENV
ENVA
ENVI
ENVX
ENZ
ENZN
EOG
EOLS
EOSS
EPAC
EPAM
EPAY
EPD
EPE
EPM
EPR
EPRT
EPZM
EQ
EQC
EQIX
EQM
EQR
EQRX
EQT
ERAS
ERII
ERNA
ES
ESAB
ESAC
ESBA
ESCA
ESL
ESMT
ESOA
ESP
ESPR
ESRT
ESRX
ESS
ESTA
ESTC
ETD
ETM
ETN
ETNB
ETRN
ETSY
EV
EVA
EVBG
EVC
EVER
EVFM
EVK
EVLO
EVLV
EVR
EVRG
EVRI
EVTC
EW
EWCZ
EWTX
EXAS
EXC
EXEL
EXFY
EXLS
EXP
EXPD
EXPE
EXPI
EXPR
EXTN
EXTR
EYE
EYEN
EYES
EYPT
EZOO
EZPW
F
FA
FANG
FARM
FARO
FAST
FAT
FATE
FBRT
FBRX
FC
FCEL
FCFS
FCN
FCPT
FCRD
FCUV
FCX
FDC
FDMT
FDP
FDS
FDUS
FDX
FE
FEIM
FELE
FENC
FET
FF
FFIE
FFIV
FGEN
FGF
FGI
FGMCU
FHI
FHLTU
FHTX
FI
FICO
FIGS
FIP
FIS
FIT
FIVE
FIVN
FIX
FIXX
FIZZ
FKWL
FL
FLDM
FLEX
FLGT
FLIR
FLL
FLLC
FLNC
FLNT
FLOW
FLR
FLS
FLT
FLWS
FLXN
FLXS
FLYW
FMC
FMIV
FN
FNA
FNCH
FND
FNF
FNJN
FNMA
FNSR
FOA
FOCS
FOE
FOLD
FOR
FORG
FORM
FORR
FOSL
FOUR
FOX
FOXF
FOX_old
FPAC
FPAY
FPRX
FR
FRANQ
FRD
FRED
FREQ
FRGE
FRGI
FROG
FRPH
FRPT
FRSGU
FRSH
FRT
FRTA
FSCT
FSII
FSLR
FSLY
FSNB
FSP
FSR
FSRX
FSS
FSTR
FSTX
FTAI
FTCI
FTCO
FTDR
FTEK
FTI
FTII
FTK
FTLF
FTNT
FTPAU
FTRE
FTV
FUL
FULC
FUN
FUSN
FUV
FVAM
FVE
FWRD
FWRG
FXLV
GAIA
GAIN
GALT
GAMCU
GAN
GANX
GATEU
GATO
GBDC
GBIO
GBL
GBT
GBTG
GBX
GCI
GCMG
GCO
GCP
GD
GDDY
GDEN
GDNSF
GDOT
GDP
GDRX
GDYN
GE
GEF
GEHC
GEL
GEN
GENC
GEO
GEOS
GERN
GES
GETR
GETY
GFF
GFGY
GFOR
GFX
GGG
GGP
GH
GHC
GHDX
GHIX
GHL
GHM
GIA
GIDYL
GIFI
GIG
GIII
GILD
GIS
GKOS
GLDD
GLG
GLP
GLPI
GLRE
GLSI
GLT
GLTO
GLUE
GLUU
GLW
GLXZ
GLYC
GM
GME
GMED
GMFI
GMHI
GMII
GMRE
GMS
GMTX
GNE
GNK
GNL
GNRC
GNSS
GNTX
GO
GOEV
GOGO
GOLF
GOOD
GOOG
GORO
GOSS
GPC
GPCR
GPI
GPK
GPN
GPOR
GPP
GPRE
GPRO
GPS
GPX
GRA
GRAY
GRBK
GRC
GRIL
GRMM
GRMN
GRNT
GROW
GRPH
GRPN
GRSVU
GRTS
GRTX
GRUB
GRVI
GRWG
GSAT
GSBD
GSD
GSHD
GSIT
GSKY
GSRMU
GT
GTBIF
GTE
GTES
GTHX
GTII
GTLB
GTS
GTT
GTX
GTY
GURE
GVA
GWPH
GWR
GWRE
GWW
GXII
H
HA
HABT
HAE
HAIN
HAL
HALO
HARP
HAS
HASI
HAYN
HAYW
HBB
HBI
HBIO
HCA
HCAT
HCC
HCCI
HCDI
HCKT
HCMC
HCNE
HCP
HCSG
HCVI
HD
HDP
HDS
HDSN
HE
HEAR
HEI
HELE
HEP
HEPA
HES
HESM
HFC
HFFG
HGBL
HGEN
HGV
HHC
HHS
HI
HIBB
HII
HIL
HIMS
HL
HLF
HLI
HLIO
HLIT
HLLY
HLNE
HLT
HLTH
HLVX
HLX
HMHC
HMNY
HMPT
HMTV
HNGR
HNI
HNNA
HNRG
HNST
HOFT
HOG
HOLX
HOME
HOOD
HOOK
HOUR
HOUS
HOWL
HP
HPE
HPJ
HPK
HPLTU
HPP
HPQ
HQI
HQY
HR
HRB
HRC
HRI
HRL
HRMY
HROW
HRT
HRTX
HRZN
HSAQ
HSDT
HSIC
HSII
HSKA
HSON
HST
HSTM
HSY
HT
HTA
HTCR
HTGC
HTGM
HTIBP
HTLD
HTZ
HUBB
HUBG
HUBS
HUMA
HUN
HURC
HURN
HUSA
HVT
HWEL
HWKN
HWKZ
HWM
HWNI
HXL
HY
HYAC
HYACU
HYBT
HYLN
HYRE
HYZN
HZNP
HZO
IAA
IART
IAS
IBIO
IBM
IBP
IBRX
ICE
ICFI
ICHR
ICPT
ICUI
ICVX
IDA
IDCC
IDEX
IDRA
IDSY
IDXG
IDXX
IDYA
IEA
IEHC
IEP
IESC
IEX
IFF
IFIN
IGAC
IGC
IGXT
IHRT
III
IIIN
IIIV
IIN
IIPR
IIVI
IKNA
IKNX
IKT
ILMN
IMAQ
IMAX
IMBI
IMDZ
IMGN
IMGO
IMH
IMKTA
IMMR
IMO
IMPL
IMPV
IMRA
IMRX
IMUX
IMVT
IMXI
INAB
INBX
INCY
INDI
INFI
INFN
INFO
INFOR
INFU
INGN
INGR
INKT
INMB
INN
INNV
INOD
INOV
INSG
INSM
INSP
INST
INSW
INT
INTA
INTC
INTEQ
INTT
INTU
INUV
INVA
INVE
INVH
INZY
IO
IOBT
IONM
IONQ
IONS
IOSP
IOTS
IOVA
IP
IPAR
IPAS
IPDN
IPG
IPGP
IPHI
IPI
IPSC
IPVI
IPWR
IQV
IR
IRBT
IRDM
IRIX
IRM
IRMD
IRRX
IRT
IRTC
IRWD
ISDR
ISEE
ISO
ISPC
ISRG
ISSC
ISSM
IT
ITCI
ITG
ITGR
ITHUF
ITI
ITOS
ITRI
ITT
ITW
IVAC
IVC
IVDN
IVR
IVT
IVVD
IVZ
J
JACK
JAGX
JAKK
JAMF
JAN
JANX
JAQC
JAZZ
JBHT
JBL
JBLU
JBT
JCG
JCI
JCOM
JCP
JCS
JEF
JELD
JHG
JILL
JKHY
JLL
JMACU
JNCE
JNJ
JNPR
JOB
JOE
JOUT
JRSH
JSDA
JVA
JW-A
JWN
JXN
JYNT
K
KAI
KALA
KALU
KALV
KAMN
KANP
KAR
KBAL
KBH
KBR
KDMN
KDNY
KDP
KE
KEGX
KELYA
KEM
KEX
KEYS
KFRC
KFS
KFY
KHC
KIDS
KIM
KIN
KIND
KKR
KLAC
KLIC
KLTR
KMB
KMI
KMT
KMX
KN
KNDI
KNIT
KNSA
KNTE
KNWN
KNX
KO
KOD
KONAQ
KOP
KOPN
KOS
KPLT
KPTI
KR
KRA
KRBP
KRC
KREF
KRG
KRMD
KRO
KRON
KROS
KRTX
KRUS
KRYS
KSICU
KSPN
KSS
KSU
KTB
KTWO
KURA
KURI
KVHI
KVSA
KVSC
KVUE
KW
KWR
KYMR
KZR
LABL
LAD
LAMR
LANC
LAND
LASR
LATG
LAUR
LAWS
LAZ
LAZY
LBPH
LBRDA
LBRT
LBUY
LCAHU
LCI
LCID
LCII
LCTX
LCUT
LDI
LE
LEA
LEAF
LEAT
LECO
LEDS
LEG
LEGH
LEN
LESL
LEU
LEVI
LEXE
LFACU
LFG
LFMDP
LFST
LFUS
LFVN
LGCY
LGF-B
LGIH
LGIQ
LGL
LGND
LH
LHCG
LHX
LIAN
LIDR
LIFE
LII
LILA
LIN
LINC
LIND
LINE
LINK
LITE
LITT
LIVE
LIVN
LIVX
LIXT
LJPC
LKCRU
LKQ
LKSD
LLAP
LLNW
LLPP
LLY
LMAT
LMFA
LMNR
LMNX
LMT
LNDC
LNG
LNN
LNT
LNTH
LOCC
LOCO
LODE
LOGI
LOGM
LOPE
LORL
LOVE
LOW
LOXO
LPCN
LPG
LPLA
LPRO
LPSN
LPTH
LPTX
LQDA
LQDT
LQMT
LRCX
LRMR
LRN
LSCC
LSDI
LSEA
LSI
LSTR
LSXMA
LSYN
LTBR
LTC
LTCH
LTH
LTHM
LTRN
LTRPA
LTRX
LTUM
LUCD
LULU
LUMN
LUMO
LUNA
LUNG
LUV
LVGO
LVLT
LVLU
LVOX
LVS
LW
LWAY
LXP
LXRP
LXRX
LXU
LYB
LYEL
LYFT
LYRA
LYV
LZ
LZB
M
MA
MAA
MAC
MACK
MACQ
MAMS
MAN
MANH
MANT
MAPS
MAR
MARA
MARK
MAS
MASI
MASS
MAT
MATW
MATX
MAX
MAXR
MB
MBII
MBIO
MBLY
MBOT
MBRX
MBUU
MC
MCAC
MCAD
MCD
MCF
MCFT
MCHP
MCHX
MCK
MCMJ
MCO
MCRB
MCRI
MCW
MCY
MD
MDB
MDC
MDGL
MDH
MDIA
MDLZ
MDP
MDR
MDRRP
MDRX
MDSO
MDT
MDVL
MDXG
ME
MEC
MED
MEDF
MEDP
MEDS
MEET
MEG
MEI
MEIP
MELI
MERC
MESA
META
METC
MFON
MG
MGEE
MGLN
MGM
MGNI
MGNX
MGP
MGPI
MGRC
MGRM
MGTA
MGTX
MGY
MHH
MHK
MHLD
MHO
MIC
MICR
MICT
MIDD
MIK
MIR
MIRM
MIST
MIT
MITK
MITT
MIXT
MJCO
MKC
MKFG
MKSI
MLAB
MLKN
MLM
MLNK
MLP
MLR
MLYS
MMAC
MMI
MMM
MMMB
MMP
MMS
MMSI
MN
MNDT
MNI
MNKD
MNOV
MNPR
MNR
MNRL
MNRO
MNST
MNTK
MNTV
MO
MOBL
MOD
MODN
MODV
MOG-A
MOH
MORF
MORN
MOS
MOV
MP
MPAA
MPC
MPLN
MPLX
MPTI
MPX
MQ
MRAI
MRAM
MRC
MRCC
MRCY
MRIN
MRK
MRKR
MRLN
MRMD
MRNA
MRNS
MRO
MRSN
MRTN
MRTX
MRVI
MRVL
MSA
MSB
MSCI
MSFT
MSGE
MSGN
MSGS
MSI
MSM
MSTR
MTBC
MTCH
MTD
MTDR
MTH
MTMT
MTN
MTNB
MTOR
MTRN
MTSI
MTTR
MTW
MTX
MTZ
MU
MUDS
MULG
MUSA
MUX
MVIS
MVST
MWA
MX
MXC
MXCT
MXIM
MXL
MXWL
MYE
MYL
MYMD
MYO
MYPS
MYRG
NABL
NAII
NANO
NAPA
NARI
NATH
NATI
NATR
NAUT
NAV
NBIX
NBL
NBR
NBSE
NBST
NBY
NC
NCLH
NCMI
NCNO
NCR
NCSM
NDAQ
NDLS
NDSN
NE
NEE
NEM
NEO
NEOG
NEOS
NEP
NEPH
NERV
NES
NET
NEU
NEWR
NEWT
NEX
NEXI
NEXT
NFE
NFLX
NFTG
NGHC
NGL
NGM
NGVC
NGVT
NHC
NHHS
NHI
NHIC
NHIQ
NHTC
NI
NICK
NINE
NJR
NKE
NKLA
NKT.CO
NKTR
NKTX
NL
NLCP
NLS
NLSN
NLST
NLY
NMFC
NMRD
NMRK
NMTC
NN
NNBR
NNN
NNVC
NOC
NOG
NOTE
NOTV
NOV
NOVA
NOVNQ
NOVT
NOW
NP
NPCE
NPK
NPO
NPTN
NR
NRC
NRDS
NRDY
NREF
NRIX
NRP
NS
NSA
NSC
NSIT
NSP
NSPR
NSSC
NSTB
NSTC
NSTD
NSTG
NTAP
NTCT
NTGR
NTIC
NTIP
NTLA
NTNX
NTRI
NTST
NTUS
NUAN
NUE
NURO
NUS
NUTX
NUVA_delisted
NUVL
NVAX
NVCR
NVCT
NVDA
NVEC
NVEE
NVIV
NVR
NVRO
NVST
NVT
NVTA
NVTS
NWBO
NWE
NWHM
NWL
NWN
NWPX
NWS
NWY
NX
NXMH
NXPI
NXRT
NXST
NXTC
NXTD
NXU
O
OABI
OAK
OAS
OB
OC
OCC
OCGN
OCN
OCUL
OCX
ODFL
ODP
ODT
OEC
OEG
OFC
OFIX
OFLX
OGE
OGN
OHI
OI
OII
OIS
OKTA
OLMA
OLN
OLO
OLP
OLPX
OM
OMC
OMCL
OMED
OMER
OMGA
OMI
OMIC
OMP
ON
ONCT
ONDK
ONEM
ONTF
ONTX
ONVO
OOMA
OPCH
OPEN
OPFI
OPGN
OPI
OPK
OPRT
OPRX
OPTN
OPTT
ORA
ORBC
ORC
ORCL
ORGN
ORGO
ORIC
ORLY
ORN
ORTX
OSA
OSG
OSH
OSIS
OSPN
OSS
OSUR
OTECU
OTEL
OTEX
OTIS
OTLK
OTRK
OTTR
OUT
OVID
OVV
OXFD
OXM
OXY
P
PAA
PAG
PAGP
PAHC
PANL
PANW
PAR
PARR
PATH
PATK
PAVM
PAY
PAYA
PAYC
PAYO
PAYS
PAYX
PBH
PBI
PBPB
PBSV
PBYI
PCAR
PCG
PCH
PCMI
PCOK
PCOR
PCRX
PCT
PCTI
PCTY
PCVX
PCYG
PD
PDCE
PDCO
PDEX
PDFS
PDLI
PDM
PDSB
PE
PEAK
PEB
PEG
PEGA
PEI
PEN
PEP
PEPG
PESI
PET
PETQ
PFE
PFGC
PFHC
PFIE
PFLT
PFMT
PFPT
PFSW
PG
PGEN
PGNX
PGNY
PGRE
PGRWU
PGTI
PH
PHAT
PHM
PHR
PHUN
PI
PII
PIII
PINC
PINE
PINS
PIPR
PIR
PIRS
PJT
PK
PKD
PKE
PKG
PKI
PKOH
PL
PLAB
PLAN
PLAY
PLBY
PLCE
PLD
PLNT
PLOW
PLPC
PLRX
PLSE
PLTK
PLTR
PLUG
PLUS
PLX
PLXP
PLXS
PLYA
PLYM
PM
PMCB
PMD
PMTS
PMVP
PNM
PNNT
PNR
PNRG
PNT
PNTG
PNW
PODD
POLA
POLY
POM
POOL
POST
POWI
POWL
PPC
PPG
PPIH
PPSI
PPTA
PPYAU
PR
PRAH
PRAX
PRBM
PRCH
PRCP
PRCT
PRDO
PRFT
PRG
PRGO
PRGS
PRGX
PRIM
PRKR
PRLB
PRLD
PRM
PRO
PROG
PRPH
PRPL
PRPO
PRSO
PRSP
PRTA
PRTH
PRTK
PRTS
PRTY
PRVA
PRVB
PS
PSB
PSIX
PSMT
PSN
PSNL
PSPC
PSSR
PSTG
PSTL
PSTV
PSTX
PSX
PTC
PTCT
PTE
PTEN
PTGX
PTIC
PTIX
PTLO
PTMN
PTN
PTOCU
PTON
PTRA
PTSI
PTVE
PUBM
PUCKU
PULM
PUMP
PURE
PVAC
PVH
PWFL
PWP
PWR
PWSC
PWUP
PX
PXD
PXLW
PXMD
PXPC
PYCR
PYPL
PYXS
PYYX
PZG
PZN
PZZA
QADA
QBTS
QCOM
QDEL
QEP
QFTA
QLYS
QMCO
QNST
QOMOU
QRHC
QRTEA
QRVO
QS
QSAM
QSI
QSR
QTNA
QTNT
QTRX
QTWO
QUAD
QUIK
QUOT
QVC
RAD
RADI
RAIL
RAIN
RAMP
RANI
RAPT
RARE
RAVE
RAVN
RBBN
RBCN
RBLX
RBOT
RBTK
RCII
RCKT
RCKY
RCM
RCMT
RCUS
RDC
RDFN
RDI
RDNT
RDUS
RDVT
RDW
REAL
REEMF
REFI
REFR
REG
REGI
REGN
REI
REKR
RELL
REMI
REN
RENE
RENT
REPH
REPL
REPX
RES
RESI
RETA
REV
REVEU
REVG
REXR
REYN
REZI
RFIL
RFP
RGCO
RGEN
RGF
RGLS
RGNX
RGP
RGR
RGS
RGTI
RHE
RHI
RHP
RHT
RICK
RIDE
RIG
RIGL
RILY
RIOT
RIVN
RKDA
RKLB
RKT
RL
RLAY
RLGT
RLGY
RLH
RLYB
RMAX
RMBS
RMD
RMR
RMRI
RNA
RNG
RNGR
RNLX
ROAD
ROCR
ROG
ROIC
ROK
ROKU
ROL
ROLL
ROOT
ROP
ROST
ROT
ROVR
RP
RPAY
RPD
RPHM
RPM
RPRX
RPT
RPTX
RRC
RRD
RRGB
RRR
RRTS
RRX
RS
RSG
RSI
RSLS
RST
RSTRF
RSVR
RSYS
RTLR
RTN
RTX
RUBY
RUN
RUSHA
RUTH
RVLV
RVMD
RVNC
RVPH
RWAY
RWLK
RWT
RXDX
RXO
RXRX
RXST
RXT
RYAM
RYI
RYN
RYTM
S
SABR
SACH
SAFE
SAFM
SAGE
SAH
SAIA
SAIL
SAM
SAMA
SAMG
SANA
SANM
SANW
SAR
SATS
SAVA
SAVE
SBAC
SBG
SBGI
SBH
SBRA
SBTX
SBUX
SC
SCAQ
SCCO
SCG
SCHL
SCHN
SCI
SCL
SCLX
SCOR
SCPH
SCPL
SCS
SCSC
SCTY
SCU
SCVL
SCWO
SCWX
SCX
SCYX
SD
SDAC
SDC
SDDL
SDGR
SDON
SDPI
SDSYA
SEAC
SEAS
SEAT
SEE
SEER
SELB
SELB_delisted
SELF
SEM
SEMG
SEMR
SENEA
SENS
SERA
SES
SESN
SFE
SFIX
SFLY
SFM
SFS
SFT
SFY
SG
SGA
SGC
SGEN
SGFY
SGH
SGHT
SGLB
SGMA
SGMO
SGMS
SGMT
SGTX
SGU
SHC
SHCR
SHLDQ
SHLO
SHLS
SHLX
SHMP
SHO
SHOO
SHOS
SHPGF
SHPH
SHW
SHWZ
SHYF
SIBN
SIC
SIEN
SIF
SIG
SIGA
SILK
SINO
SINT
SIOX
SIRI
SITC
SITE
SITM
SJI
SJM
SJW
SKIN
SKLZ
SKT
SKX
SKY
SKYT
SKYW
SKYX
SLAB
SLB
SLCA
SLDB
SLDP
SLGC
SLGG
SLGN
SLM
SLNG
SLNM
SLNO
SLP
SLQT
SLRC
SLS
SLVM
SM
SMAP
SMAR
SMCI
SMED
SMG
SMHI
SMID
SMIT
SMLP
SMLR
SMMT
SMP
SMPL
SMRT
SMRT_delisted
SMSI
SMTC
SMTI
SNA
SNAP
SNBR
SNCE
SNCR
SNCY
SND
SNDR
SNDX
SNEX
SNFCA
SNH
SNOA
SNOW
SNPO
SNPS
SNRH
SNSE
SNWV
SNX
SOFI
SOFO
SOHO
SOI
SOLO
SOLY
SON
SONM
SONO
SONX
SOPA
SORL
SOTK
SOUN
SOVO
SP
SPB
SPCE
SPFX
SPG
SPGC
SPGI
SPH
SPIR
SPKE
SPLK
SPLP-PA
SPNE
SPOK
SPPI
SPR
SPRB
SPRO
SPRT
SPSC
SPT
SPWH
SPWR
SQ
SQBG
SQFTP
SQSP
SQZ
SR
SRAC
SRAX
SRC
SRCL
SRDX
SRE
SREV
SRG
SRGA
SRI
SRLP
SRNE
SRNGU
SRPT
SRRA
SRRK
SRTS
SRT_delisted
SSD
SSI
SSKN
SSNC
SSNT
SSSS
SST
SSTI
SSTK
ST
STAA
STAG
STAR
STAY
STE
STEM
STEP
STER
STFR
STGW
STHO
STIM
STLD
STML
STMP
STOK
STOR
STR
STRA
STRM
STRN
STRO
STRR
STRS
STRY
STSA
STX
STXS
STZ
SUI
SUM
SUMO
SUN
SUNW
SUP
SUPN
SURF_delisted
SVACU
SVRA
SVT
SWAG
SWAV
SWBI
SWCH
SWI
SWIM
SWK
SWKH
SWKS
SWN
SWSSU
SWTX
SWX
SXC
SXI
SXT
SYBX
SYK
SYKE
SYM
SYN
SYNA
SYNH
SYNL
SYRG
SYRS
SYX
SYY
S_delisted
T
TACO
TACT
TALK
TALO
TALS
TAP
TARA
TARS
TASK
TAST
TAYD
TA_delisted
TBCP
TBI
TBIO
TBTC
TCDA
TCI
TCMD
TCNNF
TCNT
TCO
TCON
TCPC
TCRR
TCRT
TDG
TDOC
TDS
TDUP
TDW
TDY
TEAM
TECD
TECH
TEL
TELA
TELL
TEN
TENB
TER
TERN
TERP
TESS
TETC
TEUM
TEVA
TEX
TFFP
TFX
TG
TGAN
TGEN
TGI
TGLO
TGLS
TGNA
TGT
TGTX
TGVC
TH
THC
THCP
THMA
THMO
THO
THPTF
THR
THRD
THRM
THRN
THRX
THRY
THS
TIF
TIL
TILE
TIS
TITN
TJBH
TJX
TKAT
TKNO
TKR
TLF
TLND
TLRA
TLRD
TLRY
TLS
TLYS
TM-28
TMCI
TMDX
TMHC
TMKRU
TMO
TMST
TMUS
TMX
TNC
TNDM
TNET
TNGX
TNL
TNXP
TNYA
TOL
TOST
TOWR
TPB
TPC
TPCO
TPCS
TPH
TPIC
TPL
TPR
TPVG
TPX
TR
TRC
TRCO
TRDA
TREC
TREE
TREN
TREX
TRGP
TRHC
TRIN
TRIP
TRKA
TRMB
TRN
TRNO
TRNS
TROW
TROX
TRS
TRSSF
TRTN
TRTX
TRU
TRUE
TRUP
TRVI
TSBX
TSCO
TSHA
TSLA
TSN
TSP
TSQ
TSRI
TSRO
TSS
TSSI
TST
TSVT
TT
TTC
TTCF
TTD
TTEC
TTEK
TTGT
TTI
TTMI
TTNP
TTOO
TTPH
TTSH
TTWO
TUEM
TUSK
TVAC
TVPT
TVTY
TW
TWCB
TWER
TWI
TWIN
TWKS
TWLO
TWLVU
TWNK
TWOU
TWST
TWTR
TXG
TXN
TXRH
TXT
TYGO
TYL
TYME
TYPE
TYRA
TZOO
TZUP
U
UAL
UAN
UAVS
UBA
UBER
UCTT
UDMY
UDR
UE
UEIC
UEPS
UFI
UFPT
UFS
UG
UGI
UHAL
UHS
UI
UIS
ULBI
ULCC
ULH
ULNV
ULTA
ULTI
UMH
UNF
UNFI
UNH
UNIT
UNP
UNTC
UNVR
UONE
UP
UPL
UPLD
UPS
UPST
UPWK
URBN
URI
USAC
USAK
USAP
USAU
USCR
USDP
USEG
USFD
USG
USLM
USM
USNA
USX
UTHR
UTI
UTL
UTMD
UTZ
V
VACC
VALPQ
VALU
VAPO
VAR
VATE
VC
VCRA
VCTR
VCYT
VEC
VECO
VEEV
VEL
VER
VERA
VERB
VERI
VERO
VERU
VERV
VERX
VERY
VFC
VFF
VG
VGZ
VHC
VHI
VIA
VIAV
VICI
VICR
VIDE
VIGL
VIR
VIRX
VIVE
VIVK
VIVO
VKTX
VLD
VLDR
VLGEA
VLO
VLRX
VLTA
VMC
VMEO
VMGAU
VMI
VMW
VNCE
VNDA
VNE
VNJA
VNO
VNOM
VNRX
VNT
VNTV
VOLT
VOR
VORB
VOXX
VPCC
VPG
VRA
VRAR
VRAY
VRCA
VRDN
VRDR
VRE
VREX
VRM
VRML
VRNA
VRNOF
VRNS
VRNT
VRRM
VRS
VRSK
VRSN
VRT
VRTS
VRTU
VRTV
VRTX
VSAC
VSAT
VSBC
VSCO
VSEC
VSH
VSLR
VSM
VSTM
VSTO
VTGN
VTIQ
VTLE
VTOL
VTR
VTRS
VTSI
VTVT
VTYX
VUZI
VVI
VVNT
VVV
VWTR
VXRT
VYGR
VZ
VZIO
W
WAB
WAIR
WAT
WATT
WBA
WBC
WBD
WBEV
WBT
WCC
WCG
WCN
WDAY
WDC
WDFC
WDQ
WE
WEAV
WEC
WELL
WEN
WERN
WES
WEST
WETF
WEWA
WEYS
WFCF
WFRD
WGL
WGO
WHD
WHG
WHR
WIFI
WIN
WINA
WING
WINV
WIRE
WISH
WK
WKHS
WLB
WLDN
WLFC
WLK
WLKP
WLL
WM
WMB
WMG
WMGI_delisted
WMK
WMS
WMT
WNC
WOLF
WOOF
WOR
WORK
WOW
WPC
WPG
WPX
WR
WRAC
WRBY
WRE
WRI
WRK
WRPT
WSC
WSM
WSR
WST
WSTG
WSTL
WTI
WTRG
WTRH
WTS
WTTR
WTW
WU
WVE
WW
WWD
WWE
WWR
WWW
WY
WYNN
X
XAIR
XBIO
XBIT
XCO
XEC
XEL
XENE
XENT
XERS
XFIN
XFOR
XGN
XHR
XL
XLNX
XLO
XLRN
XM
XMTR
XNCR
XOG_delisted
XOM
XOMA
XONE
XOS
XOXO
XPDB
XPEL
XPER
XPO
XPOF
XPRO
XRAY
XRX
XSPA
XTNT
XXII
XYL
Y
YELL
YELP
YETI
YEXT
YGYI
YMAB
YOGAQ
YORW
YOU
YTEN
YUM
YUMC
Z
ZAGG
ZAYO
ZBH
ZBRA
ZDGE
ZEN
ZETA
ZEUS
ZEV
ZGNX
ZI
ZIMV
ZIP
ZIVO
ZIXI
ZM
ZNGA
ZNOG
ZNTE
ZNTL
ZOM
ZS
ZTS
ZUMZ
ZUO
ZUUS
ZVIA
ZVO
ZY
ZYNE
ZYXI

In [134]:
df_ticker = df_quarterly[df_quarterly['Ticker'] == 'MSFT']
df_ticker = finance_stat_rename_columns('income', df_ticker)
df_ticker = df_ticker.reset_index("report_date")
merge_df_to_pg(df_ticker, engine, table_name, schema_name, merge_key)

In [114]:
df_ticker.to_sql(table_name, engine, schema=schema_name, if_exists='append', index=False)
print(f"DataFrame saved to {table_name} table in PostgreSQL database.")

DataFrame saved to income table in PostgreSQL database.

In [94]:
def finance_stat_rename_columns(df_type, df):
    if df_type == 'income':
        df = df.rename(columns={
            'Ticker': 'ticker', 
            'SimFinId': 'simfin_id', 
            'Currency': 'currency', 
            'Fiscal Year': 'fiscal_year', 
            'Fiscal Period': 'fiscal_period',
            'Publish Date': 'publish_date', 
            'Restated Date': 'restated_date', 
            'Shares (Basic)': 'shares_basic', 
            'Shares (Diluted)': 'shares_diluted',
            'Revenue': 'revenue', 
            'Cost of Revenue': 'cost_of_revenue', 
            'Gross Profit': 'gross_profit', 
            'Operating Expenses': 'operating_expenses',
            'Selling, General & Administrative': 'selling_general_administrative', 
            'Research & Development': 'research_development',
            'Depreciation & Amortization': 'depreciation_amortization', 
            'Operating Income (Loss)': 'operating_income',
            'Non-Operating Income (Loss)': 'non_operating_income', 
            'Interest Expense, Net': 'interest_expense_net',
            'Pretax Income (Loss), Adj.': 'pretax_income_adj', 
            'Abnormal Gains (Losses)': 'abnormal_gains',
            'Pretax Income (Loss)': 'pretax_income', 
            'Income Tax (Expense) Benefit, Net': 'income_tax_benefit_net',
            'Income (Loss) from Continuing Operations': 'income_from_continuing_operations',
            'Net Extraordinary Gains (Losses)': 'net_extraordinary_gains',
            'Net Income': 'net_income',
            'Net Income (Common)': 'net_income_common'
        })
        df.rename_axis('report_date', inplace=True)
    return df

In [115]:
from sqlalchemy import Table, MetaData
from sqlalchemy.dialects.postgresql import insert
schema_name = 'finance'
table_name = 'income'

In [126]:
df_ticker.head()

,report_date,ticker,simfin_id,currency,fiscal_year,fiscal_period,publish_date,restated_date,shares_basic,shares_diluted,revenue,cost_of_revenue,gross_profit,operating_expenses,selling_general_administrative,research_development,depreciation_amortization,operating_income,non_operating_income,interest_expense_net,pretax_income_adj,abnormal_gains,pretax_income,income_tax_benefit_net,income_from_continuing_operations,net_extraordinary_gains,net_income,net_income_common
0,2018-09-30,AAPL,111052,USD,2018,Q4,2018-11-05,2020-10-30,1.920635e+10,1.939019e+10,6.290000e+10,-3.881600e+10,2.408400e+10,-7.966000e+09,-4.216000e+09,-3.750000e+09,NaN,1.611800e+10,303000000.0,442739444.0,1.642100e+10,NaN,16421000000,-2.296000e+09,14125000000,NaN,14125000000,14125000000
1,2018-12-31,AAPL,111052,USD,2019,Q1,2019-01-30,2020-01-29,1.894328e+10,1.909301e+10,8.431000e+10,-5.227900e+10,3.203100e+10,-8.685000e+09,-4.783000e+09,-3.902000e+09,NaN,2.334600e+10,560000000.0,416301193.0,2.390600e+10,NaN,23906000000,-3.941000e+09,19965000000,NaN,19965000000,19965000000
2,2019-03-31,AAPL,111052,USD,2019,Q2,2019-05-01,2020-05-01,1.869628e+10,1.880258e+10,5.801500e+10,-3.619400e+10,2.182100e+10,-8.406000e+09,-4.458000e+09,-3.948000e+09,NaN,1.341500e+10,378000000.0,347872558.0,1.379300e+10,NaN,13793000000,-2.232000e+09,11561000000,NaN,11561000000,11561000000
3,2019-06-30,AAPL,111052,USD,2019,Q3,2019-07-31,2020-07-31,1.828253e+10,1.840552e+10,5.380900e+10,-3.358200e+10,2.022700e+10,-8.683000e+09,-4.426000e+09,-4.257000e+09,NaN,1.154400e+10,367000000.0,324185526.0,1.191100e+10,NaN,11911000000,-1.867000e+09,10044000000,NaN,10044000000,10044000000
4,2019-09-30,AAPL,111052,USD,2019,Q4,2019-10-31,2021-10-29,1.796325e+10,1.808150e+10,6.404000e+10,-3.972700e+10,2.431300e+10,-8.688000e+09,-4.578000e+09,-4.110000e+09,NaN,1.562500e+10,502000000.0,295590714.0,1.612700e+10,NaN,16127000000,-2.441000e+09,13686000000,NaN,13686000000,13686000000

In [125]:
df_ticker.shape

(20, 28)

In [127]:
df_ticker.groupby(['report_date', 'ticker']).agg({'ticker': 'count'})

                    ticker
report_date ticker
2018-09-30  AAPL         1
2018-12-31  AAPL         1
2019-03-31  AAPL         1
2019-06-30  AAPL         1
2019-09-30  AAPL         1
2019-12-31  AAPL         1
2020-03-31  AAPL         1
2020-06-30  AAPL         1
2020-09-30  AAPL         1
2020-12-31  AAPL         1
2021-03-31  AAPL         1
2021-06-30  AAPL         1
2021-09-30  AAPL         1
2021-12-31  AAPL         1
2022-03-31  AAPL         1
2022-06-30  AAPL         1
2022-09-30  AAPL         1
2022-12-31  AAPL         1
2023-03-31  AAPL         1
2023-06-30  AAPL         1

In [129]:
merge_key = ['report_date', 'ticker']
metadata = MetaData()
table = Table(table_name, metadata, autoload_with=engine, schema=schema_name)

# Define the insert statement
insert_stmt = insert(table).values(df_ticker.to_dict(orient='records'))

# Define the update statement for the ON CONFLICT clause
update_stmt = insert_stmt.on_conflict_do_update(
    index_elements=merge_key,  # Specify the unique constraint or index for conflict
    set_={c.key: c for c in insert_stmt.excluded if c.key not in merge_key}
)

# Execute the upsert
with engine.connect() as conn:
    conn.execute(update_stmt)

C:\Users\p.kravchuk\AppData\Roaming\MobaXterm\slash\tmp\ipykernel_21556\977384186.py:16: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  conn.execute(update_stmt)

In [132]:
def merge_df_to_pg(df, engine, table_name, schema_name, merge_key):
    metadata = MetaData()
    table = Table(table_name, metadata, autoload_with=engine, schema=schema_name)

    # Define the insert statement
    insert_stmt = insert(table).values(df.to_dict(orient='records'))

    # Define the update statement for the ON CONFLICT clause
    update_stmt = insert_stmt.on_conflict_do_update(
        index_elements=merge_key,  # Specify the unique constraint or index for conflict
        set_={c.key: c for c in insert_stmt.excluded if c.key not in merge_key}
    )

    # Execute the upsert
    with engine.connect() as conn:
        conn.execute(update_stmt)

### Собираем все вместе

In [ ]:
import sys
import os
from dotenv import load_dotenv
import simfin as sf

In [ ]:
load_dotenv()
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [135]:
from app import FinanceLib as fl

In [136]:
simfin_api_key = os.getenv("SIMFIN_API_KEY")
# Set your API-key for downloading data. This key gets the free data.
sf.set_api_key(simfin_api_key)
# Set the local directory where data-files are stored.
# The directory will be created if it does not already exist.
sf.set_data_dir('~/simfin_data/')

In [137]:
# Create SQLAlchemy engine
engine = fl.get_conn_pg_engine(False)

In [138]:
schema_name = 'finance'

#### 1. Income

In [139]:
REPORT_DATE, PUBLISH_DATE, RESTATED_DATE = 'Report Date', 'Publish Date', 'Restated Date'

df_quarterly = sf.load(dataset='income', variant='quarterly', market='us', refresh_days=3,
              index=[REPORT_DATE],
              parse_dates=[REPORT_DATE, PUBLISH_DATE, RESTATED_DATE])

Dataset "us-income-quarterly" on disk (0 days old).
- Loading from disk ...

C:\Projects\finance-venv\lib\site-packages\simfin\load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,

Done!

In [140]:
table_name = 'income'

In [141]:
income_tickers = df_quarterly.groupby('Ticker').agg({'Ticker': 'count'})
income_tickers = income_tickers.rename(columns={'Ticker': 'CountRows'})

In [144]:
for ticker in income_tickers.index:
    print(ticker)
    if '_delisted' not in ticker:        
        df_ticker = df_quarterly[df_quarterly['Ticker'] == ticker]
        df_ticker = fl.simfin_rename_columns('income', df_ticker)
        df_ticker = df_ticker.reset_index("report_date")
        fl.merge_df_to_pg(df_ticker, engine, table_name, schema_name, merge_key)

A
AA
AAC
AACI
AAC_delisted
AAL
AAMC
AAOI
AAP
AAPL
AAT
AAWH
AAWW
ABBV
ABCD
ABCL
ABEO
ABG
ABIO
ABMC
ABMD
ABNB
ABOS
ABSI
ABT
ABTL
ABUS
ABVC
AC
ACA
ACAC
ACAD
ACAH
ACAN
ACAQ
ACBA
ACC
ACCO
ACEL
ACER
ACET
ACET_delisted
ACHC
ACHR
ACHV
ACI
ACIA
ACIW
ACLS
ACLX
ACM
ACMR
ACN
ACOR
ACRE
ACRO
ACRS
ACRX
ACST
ACTG
ACU
ACVA
ACXP
ADAP
ADBE
ADC
ADER
ADES
ADI
ADIL
ADM
ADMA
ADMP
ADMS
ADNT
ADOM
ADP
ADRA
ADRT
ADSK
ADT
ADTN
ADUS
ADV
ADVM
AE
AEE
AEHA
AEHR
AEMD
AEO
AEP
AERC
AERG
AERI
AES
AESE
AESI
AEVA
AFCG
AFGS
AFI
AFRM
AGCO
AGEN
AGFS
AGHI
AGIO
AGM
AGN
AGNC
AGR
AGS
AGTI
AGX
AGYS
AH
AHCO
AHH
AHPI
AI
AIM
AIMC
AIMD
AIP
AIR
AIRC
AIRG
AIRS
AIRTP
AIT
AIV
AJG
AJIA
AJRD
AKA
AKAM
AKBA
AKLI
AKOM
AKRO
AKRX
AKS
AKYA
AL
ALB
ALBO
ALCC
ALCO
ALDX
ALE
ALEC
ALEX
ALG
ALGM
ALGN
ALGS
ALGT
ALHC
ALIM
ALJJ
ALK
ALKS
ALKT
ALLE
ALLK
ALLO
ALNA
ALNY
ALPA
ALPN
ALRM
ALRN
ALSK
ALSN
ALT
ALTG
ALTM
ALTMS
ALTO
ALTR
ALUR
ALVR
ALX
ALXN
ALXO
ALZN
AMAM
AMAT
AMC
AMCIU
AMCR
AMCX
AMD
AME
AMED
AMG
AMGN
AMH
AMHCU
AMK
AMKR
AMLX
AMN
AMOT
AMP
AMPE
AMPH
AMPL
AMPY
AMR
AMRC
AMRN
AMRS
AMRX
AMSC
AMSWA
AMT
AMTD
AMTX
AMWD
AMWL
AMZN
AN
ANAB
ANDE
ANET
ANF
ANGI
ANGO
ANIK
ANIP
ANIX
ANNX
ANSS
ANVS
ANY
ANZU
AOMR
AON
AORT
AOS
AOUT
AP
APA
APAM
APC
APD
APDN
APEI
APEN
APG
APGE
APH
APHE
APLD
APLS
APLT
APMI
APO
APOG
APOP
APP
APPF
APPH
APPN
APPS
APRE
APRN
APT
APTI
APTV
APTX
APU
APVO
APXI
APY
APYX
AQB
AQMS
AQST
AQUA
AR
ARA
ARAV
ARAY
ARC
ARCB
ARCH
ARCT
ARCW
ARDX
AREC
AREX
ARHS
ARIS
ARKO
ARKR
ARL
ARLO
ARLP
ARMK
ARMP
ARNA
ARNC
AROC
ARPO
ARQL
ARQT
ARRW
ARRY
ARRY_delisted
ARTE
ARTNA
ARTX
ARVN
ARW
ARWR
ASAN
ASCMA
ASFH
ASGN
ASIX
ASLE
ASMB
ASNA
ASO
ASPN
ASPU
ASRT
ASTC
ASTE
ASTR
ASTS
ASUR
ASXC
ASYS
ATCX
ATEC
ATEN
ATER
ATEX
ATGE
ATHA
ATHN_delisted
ATHX
ATI
ATKR
ATLC
ATMU
ATNI
ATNM
ATNX
ATO
ATOM
ATOS
ATR
ATRA
ATRC
ATRI
ATRO
ATRS
ATSG
ATUS
ATVCU
ATVI
ATXG
ATXS
AUGG
AUGX
AUMN
AUPH
AUR
AURA
AUVI
AVAC
AVAH
AVAV
AVB
AVD
AVDL
AVDX
AVEO
AVGO
AVGR
AVID
AVIR
AVLR
AVMR
AVNS
AVNT
AVP
AVPT
AVRO
AVT
AVTE
AVTR
AVY
AVYA
AWI
AWK
AWR
AWRE
AXAS
AXDX
AXGN
AXL
AXNX
AXON
AXSM
AXTA
AXTI
AY
AYI
AYX
AZEK

KeyboardInterrupt:

### 2. Balance

In [145]:
REPORT_DATE, PUBLISH_DATE, RESTATED_DATE = 'Report Date', 'Publish Date', 'Restated Date'

df_quarterly = sf.load(dataset='balance', variant='quarterly', market='us', refresh_days=3,
              index=[REPORT_DATE],
              parse_dates=[REPORT_DATE, PUBLISH_DATE, RESTATED_DATE])

Dataset "us-balance-quarterly" not on disk.
- Downloading ... 100.0%
- Extracting zip-file ... Done!
- Loading from disk ...

C:\Projects\finance-venv\lib\site-packages\simfin\load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,

Done!

In [146]:
df_quarterly.columns

Index(['Ticker', 'SimFinId', 'Currency', 'Fiscal Year', 'Fiscal Period',
       'Publish Date', 'Restated Date', 'Shares (Basic)', 'Shares (Diluted)',
       'Cash, Cash Equivalents & Short Term Investments',
       'Accounts & Notes Receivable', 'Inventories', 'Total Current Assets',
       'Property, Plant & Equipment, Net',
       'Long Term Investments & Receivables', 'Other Long Term Assets',
       'Total Noncurrent Assets', 'Total Assets', 'Payables & Accruals',
       'Short Term Debt', 'Total Current Liabilities', 'Long Term Debt',
       'Total Noncurrent Liabilities', 'Total Liabilities',
       'Share Capital & Additional Paid-In Capital', 'Treasury Stock',
       'Retained Earnings', 'Total Equity', 'Total Liabilities & Equity'],
      dtype='object')

In [147]:
df_quarterly.head(5)

,Ticker,SimFinId,Currency,Fiscal Year,Fiscal Period,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),"Cash, Cash Equivalents & Short Term Investments",Accounts & Notes Receivable,Inventories,Total Current Assets,"Property, Plant & Equipment, Net",Long Term Investments & Receivables,Other Long Term Assets,Total Noncurrent Assets,Total Assets,Payables & Accruals,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity
Report Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-09-30,AWRE,512152,USD,2018,Q3,2018-10-26,2018-10-26,21564000.0,21639000.0,4.896300e+07,7.499604e+06,NaN,5.686300e+07,4.128000e+06,NaN,5.199000e+06,9.327000e+06,66190000,1.893000e+06,NaN,4.931000e+06,NaN,7.700000e+04,5.008000e+06,9.651400e+07,NaN,-3.533200e+07,61182000,66190000
2018-09-30,EVA,900872,USD,2018,Q3,2018-11-09,2018-11-09,23893000.0,36813000.0,8.630000e+05,5.461311e+07,3.432200e+07,9.151500e+07,5.524560e+08,NaN,9.039800e+07,6.428540e+08,734369000,8.960309e+07,7070000.0,9.651100e+07,4.024470e+08,4.821140e+08,5.786250e+08,1.551090e+08,NaN,NaN,155744000,734369000
2018-09-30,LEA,610198,USD,2018,Q3,2018-10-25,2018-10-25,65372829.0,65868660.0,1.198600e+09,3.301800e+09,1.285200e+09,6.567700e+09,2.536200e+09,NaN,2.905500e+09,5.441700e+09,12009400000,4.753461e+09,17200000.0,4.779900e+09,1.946600e+09,2.632200e+09,7.412100e+09,1.176700e+09,-1.181700e+09,4.953800e+09,4284170055,12009400000
2018-09-30,GTHX,820499,USD,2018,Q3,2018-11-07,2018-11-07,33829437.0,33829437.0,3.905240e+08,NaN,NaN,3.920130e+08,1.006000e+06,NaN,NaN,1.006000e+06,393019000,1.217171e+07,NaN,1.367400e+07,NaN,9.000000e+04,1.376400e+07,5.695780e+08,-8.000000e+03,-1.903150e+08,379255000,393019000
2018-09-30,EVBG,914618,USD,2018,Q3,2018-11-09,2018-11-09,29460156.0,29460156.0,1.031270e+08,3.703300e+07,NaN,1.548040e+08,2.918000e+06,NaN,9.686600e+07,9.978400e+07,254588000,2.176200e+07,432000.0,1.056990e+08,9.291600e+07,1.011660e+08,2.068650e+08,1.879380e+08,NaN,-1.378650e+08,47723000,254588000